FROM nginx:latest
COPY ZyzzyvagRPC/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ZyzzyvagRPC/nginx/zyzzyva.tld.chained.crt /etc/ssl/private/zyzzyva.tld.chained.crt
COPY ZyzzyvagRPC/nginx/zyzzyva.tld.key /etc/ssl/private/zyzzyva.tld.key
